### PR TITLE
Make so quiz_dir can be NULL

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?

This is still related to #82 The checks were failing and I was adding a fix for that.

### CODE REVIEW

**Review by carriewright11 — COMMENTED** [review]
should output_dir be output dir too?

**Comment by cansavvy** [comment]
No. I misunderstood the fail. I was right the first time, but it's the vignette that is failing because in the vignette I didn't put the quizzes in a folder.

**Comment by carriewright11** [comment]
is the fail due to https://github.com/jhudsl/leanbuild/blob/master/R/example_data.R

**Comment by carriewright11** [comment]
> > No. I misunderstood the fail. I was right the first time, but it's the vignette that is failing because in the vignette I didn't put the quizzes in a folder.
> 
> At least not the first time I run `bookdown_to_leanpub()`

ah just saw this.. yeah makes sense

**Comment by cansavvy** [comment]
It didn't have to do with copy_quizzes() at all, it was because if you use quiz_dir = NULL then the making book.txt part of the function fails, but now I put in some logic around that.

**Comment by cansavvy** [comment]
Great! I think this is all set!

**Comment by carriewright11** [comment]
> Great! I think this is all set!

YAY looks good!

**Pull request merged**
